name: "Public Support Collection"
pipelines:
  - slug: "clean_questions_publicsupport"
    sources:
      - slack_support_channels   
    destination: cleaned-questions-publicsupport
    transformations: 
      - new_columns
      - questions_dataframe
  
  - slug: "clean_answers_publicsupport"
    sources:
      - slack_support_channels
    destination: cleaned-answers-publicsupport
    transformations:
      # - new_columns
      - answers_dataframe

  - slug: "merge_messages_publicsupport"
    sources:
      - cleaned-questions-publicsupport  # Output from clean_questions_publicsupport
      - cleaned-answers-publicsupport   #Output from clean_answers_publicsupport
    destination: cleaned-support-channels
    transformations:
      - merge_dataframes
